language: node_js
node_js:
  - 16
cache:
  npm: false
before_script:
  - npm run info:version
script:
#  - npm ci
  - npm test
  #- npm run build
#after_script:
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
